# Numpy 
14jan2023

session1


- Numerical Python
- Numerical Array
- Fastest
- Vectorized Operation
- Contigious Memory

Numpy is array

In [1]:

import numpy as np


In [2]:
#Create a numpy array
#creating an array using a python list
x = np.array([22,33,44,55])

In [3]:
x

array([22, 33, 44, 55])

In [4]:
x.size

4

In [5]:
x.shape
# 1d arary = Vector
# 2d = Matrix
# 3d = Cube

(4,)

In [6]:
#dimensions
x.ndim

1

In [7]:
arr1d = np.arange(10)
arr1d 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#same as we have in python
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
arr2d = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [10]:
arr2d.shape

(4, 3)

In [11]:
arr2d = np.arange(20).reshape(1,20)
# arr2d = np.arange(20).reshape(20,1)
# arr2d = np.arange(20).reshape(4,5)
# arr2d = np.arange(20).reshape(5,4)
# arr2d = np.arange(20).reshape(10,10)

In [12]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [13]:
type(arr2d)

numpy.ndarray

In [14]:
arr2d.shape

(1, 20)

In [15]:
arr2d.ndim

2

In [16]:
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
arr = np.array(10)
arr

array(10)

In [20]:
arr.ndim

0

In [21]:
arr = np.array([[10]]) #2dmatric
arr

array([[10]])

In [22]:
arr.ndim

2

In [23]:
arr2d = np.arange(20).reshape(20,1)
arr2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [24]:
arr3d = np.arange(64).reshape(4,4,4) #(depth, rows and columns)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [25]:
arr3d1 = np.arange(144).reshape(9,4,4) #(depth, rows and columns)
arr3d1

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]],

       [[ 64,  65,  66,  67],
        [ 68,  69,  70,  71],
        [ 72,  73,  74,  75],
        [ 76,  77,  78,  79]],

       [[ 80,  81,  82,  83],
        [ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95]],

       [[ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123],
        [124, 125, 126, 127]],

       [[128, 129, 130, 

In [26]:
arr3d[1,3]

array([28, 29, 30, 31])

In [27]:
arr3d[1][2]

array([24, 25, 26, 27])

In [28]:
arr3d[2,1,2]

38

In [29]:
x

array([22, 33, 44, 55])

In [30]:
z = []
for n in x:
  z.append(n * 2)
z


[44, 66, 88, 110]

In [31]:
[n**2 for n in x]

[484, 1089, 1936, 3025]

In [32]:
x * 2

array([ 44,  66,  88, 110])

In [33]:
arr2d / 10

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ],
       [1.1],
       [1.2],
       [1.3],
       [1.4],
       [1.5],
       [1.6],
       [1.7],
       [1.8],
       [1.9]])

In [34]:
arr3d *  10 #These operation are known as vetorized

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110],
        [120, 130, 140, 150]],

       [[160, 170, 180, 190],
        [200, 210, 220, 230],
        [240, 250, 260, 270],
        [280, 290, 300, 310]],

       [[320, 330, 340, 350],
        [360, 370, 380, 390],
        [400, 410, 420, 430],
        [440, 450, 460, 470]],

       [[480, 490, 500, 510],
        [520, 530, 540, 550],
        [560, 570, 580, 590],
        [600, 610, 620, 630]]])

In [35]:
x

array([22, 33, 44, 55])

In [36]:
y = np.arange(4)

In [37]:
y

array([0, 1, 2, 3])

In [38]:
x+y

array([22, 34, 46, 58])

ValueError: cannot reshape array of size 64 into shape (9,4,4)

In [39]:
a = np.arange(25).reshape(5,5)
b = np.arange(25, 50).reshape(5,5)

In [40]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [42]:
a + b

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [43]:
a * b

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [44]:
a@b
#a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

# Array Slicing

In [45]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
a[2,3]

13

In [47]:
#slicing
# array [row, col]
#       [start:end, start:end] # this is sclicing

In [48]:
a[2:3, 3:4]

array([[13]])

In [49]:
a[1:4,3]

array([ 8, 13, 18])

In [50]:
a[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [51]:
a[1:4, 3:4]

array([[ 8],
       [13],
       [18]])

In [52]:
a[:4]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
a[4,:4]

array([20, 21, 22, 23])

# Querrying Array

In [54]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
mask = a>5   #Mask
mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [56]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [57]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
a[a>7] = 100

In [59]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [60]:
np.where(a>10, 0, a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [61]:
a[(a%2==0 & (a%7==0))]

array([  0,   2,   4,   6, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100])

In [62]:
a[(a%2==0 | (a%7==0))]

array([  2,   4,   6,   7, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100])

In [63]:
np.where((a%2==0) | (a%7==0), "Wow", "Oh")

array([['Wow', 'Oh', 'Wow', 'Oh', 'Wow'],
       ['Oh', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow']], dtype='<U3')

In [64]:
np.concatenate((a,b), axis=0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [65]:
np.concatenate((a,b), axis=0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [66]:
np.stack((a,b))

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]]])

In [67]:
np.hstack((a,b))

array([[  0,   1,   2,   3,   4,  25,  26,  27,  28,  29],
       [  5,   6,   7, 100, 100,  30,  31,  32,  33,  34],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  40,  41,  42,  43,  44],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49]])

In [68]:
np.vstack((a,b))

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])